###############################################################################
#
#     OPTIONAL ARGUMENTS   **** LOOK HERE IF YOU HAVE TROUBLE COMPILING ****
#
#     -DCORE        - Disables core dump limits. (Default behavior is to
#                     not allow core dumps unless ./core already exists.)
#                     If you don't have setrlimit, use this.
#
#     -DHAVE_XPM    - Enable XPM support. This requires the XPM library, 
#                     available from prep.ai.mit.edu:contrib/xpm-*.tar.Z.  
#                     Version 3.2f is the earliest version supported.  
#                     If you enable XPM supprt, uncomment the XPM_LIB line
#
#     -DINTERNAL_SP - Use the internal specpr requestor rather than the
#                     similar, external program 'sp'.
#
# If you arte using thje native HP compiler, you will need to add -Ae
# to the CCOPTS line
#
###############################################################################

CCOPTS=-g -DCORE  -DHAVE_XPM

###############################################################################
#     If your X include files and libraries are not in the standard place,
#     uncommment these lines and make sure they point to the proper places.
###############################################################################

X_INCLUDES=-I/usr/include/X11R5 -I/usr/openwin/include
X_LIBS=-L/usr/lib/X11R5 -I/usr/openwin/lib -L/usr/X11R6/lib

###############################################################################
#     If your Xpm library is in a funny place, add a -Lpath option here.
#     If you have disabled XPM support, comment out the following line.
###############################################################################

XPM_LIB=-L../xpm/lib -lXpm

###############################################################################
# Destination directory for executables
###############################################################################

BINDIR=/opt/local/bin

###############################################################################
#
# For Solaris, you will probably need this
#
###############################################################################
EXTRA_LIBS=-lsocket

###############################################################################
#
# You shouldn't have to change anything below here.
#
###############################################################################

CFLAGS=$(CCOPTS) -I.. -I../lib -I../iomedley $(X_INCLUDES)
# -O
LIBS=-L../lib -L../iomedley -liomedley $(X_LIBS) $(XPM_LIB) -lXfred -lX11 -lm $(EXTRA_LIBS) 

PWDIR=../pw

sp_source: pw_src
	@cd sp ; $(MAKE) "CC=$(CC)" "CFLAGS=$(CFLAGS)" "LIBS=$(LIBS)"

iomedley_src:
	@cd iomedley && $(MAKE) "CC=$(CC)" "CFLAGS=$(CFLAGS)" "LIBS=$(LIBS)"

pw_src:	lib_source iomedley_src
	@cd pw ; $(MAKE) "CC=$(CC)" "CFLAGS=$(CFLAGS)" "LIBS=$(LIBS)"

lib_source:
	@cd lib ; $(MAKE) "CC=$(CC)" "CFLAGS=$(CFLAGS)" "LIBS=$(LIBS)"

install:	sp
	cp pw/pw $(BINDIR)
	cp sp/sp $(BINDIR)

dist:	clean
	echo pw-`head -1 pw/version.h | sed -e 's/.*#//;s/".*//'` > .ver
	rm -rf `cat .ver`
	mkdir `cat .ver` 
	(cd `cat .ver` ; mkdir pw lib sp iomedley ; ln -s ../bitmaps .)
	ln README Makefile `cat .ver`
	ln pw/*.[ch] pw/Makefile 	 `cat .ver`/pw
	ln lib/*.[ch] lib/Makefile 	 `cat .ver`/lib
	ln iomedley/*.[ch] iomedley/Makefile 	 `cat .ver`/iomedley
	ln sp/*.[ch] sp/Makefile	 `cat .ver`/sp
	tar cohf `cat .ver`.tar `cat .ver`
	compress `cat .ver`.tar
	rm -rf `cat .ver`

move_dist:  dist
	compress -c pw.tar > pw-`head -1 pw/version.h | sed -e 's/.*#//;s/".*//'`.tar.Z

mirror:
	-mkdir lib pw sp
	(cd lib ; ln -s ../$(PWDIR)/lib/*.[ch] ../$(PWDIR)/lib/Makefile .)
	(cd pw ; ln -s ../$(PWDIR)/pw/*.[ch] ../$(PWDIR)/pw/Makefile .)
	(cd sp ; ln -s ../$(PWDIR)/sp/*.[ch] ../$(PWDIR)/sp/Makefile .)
	-ln -s $(PWDIR)/bitmaps .
	-cp $(PWDIR)/Makefile .

clean:
	cd lib ; $(MAKE) clean
	cd iomedley ; $(MAKE) clean
	cd pw ; $(MAKE) clean
	cd sp ; $(MAKE) clean
