#include "Bitmap_Info.h"
#include "Bitmap_Magnify.h"
#include "Bitmap_Spectra.h"
#include "Bitmap_Folder.h"
#include "Bitmap_Button_Up.h"
#include "Bitmap_Button_Down.h"
#include "Bitmap_Write.h"
#include "Bitmap_Image.h"
#include "Bitmap_Arrows.h"
#include "Bitmap_Cube.h"
#include "Bitmap_Rotate.h"
#include "Bitmap_Unzoom.h"
#include "Bitmap_Zoom.h"

#include "25pt/File.xbm"
#include "25pt/Help.xbm"
#include "25pt/Magnify.xbm"
#include "25pt/Plot.xbm"
#include "25pt/Window.xbm"
#include "25pt/Write.xbm"

#include "math/Bitmap_Equal.h"
#include "math/Bitmap_Divide.h"
#include "math/Bitmap_Integral.h"
#include "math/Bitmap_Minus.h"
#include "math/Bitmap_Mult.h"
#include "math/Bitmap_Plus.h"
#include "math/Bitmap_Sigma.h"
#include "math/Bitmap_Zero.h"

#include "15pt/Bitmap_Arrow_Up_15.h"
#include "15pt/Bitmap_Arrow_Down_15.h"

#include "20pt/Write_20.h"

#include "Bitmap_Page_Up.h"
#include "Bitmap_Scroll_Up.h"
#include "Bitmap_Page_Down.h"
#include "Bitmap_Scroll_Down.h"
#include "Bitmap_CheckMark.h"
#include "Bitmap_Copy.h"
#include "Bitmap_Append.h"
