#
# Makefile to build libXfred.a
#
CC=gcc
RANLIB=ranlib

DEFS=-DHAVE_CONFIG_H
CPPFLAGS=
CFLAGS=-g -O2 -I/usr/include/X11

OBJ=Button.o Slider.o VisInfo.o Joystick.o MapAndWait.o init.o AMap.o \
    List.o xgets.o chd.o toggle.o confirm.o hershey.o Composite.o \
    LB.o MB.o PB.o RB.o CB.o XB.o xf.o misc.o 3D.o

libXfred.a:	$(OBJ) Xfred.h
	@echo "*** Making Xfred library ***"
	-rm -f libXfred.a
	ar cqv libXfred.a $(OBJ)
	$(RANLIB) libXfred.a

clean:
	rm -f $(OBJ) libXfred.a

.c.o:
	$(CC) -c $(DEFS) $(CPPFLAGS) $(CFLAGS) $<

############################################################################
# DEPENDANCIES
############################################################################
Button.o:	Button.c Xfred.h Button.h Callback.h VisInfo.h
Slider.o:	Slider.c Xfred.h Slider.h VisInfo.h
VisInfo.o:	VisInfo.c VisInfo.h
Joystick.o:	Joystick.c Xfred.h Callback.h VisInfo.h Joystick.h
MapAndWait.o:	MapAndWait.c
init.o:		init.c
AMap.o:		AMap.c Xfred.h AMap.h Callback.h VisInfo.h
List.o: 	Button.c Slider.c Button.h Slider.h List.h VisInfo.h Callback.h
hershey.o:	hershey.c hershey.h
